- hosts: localhost
  tasks:
  - name: "Ansible | Creating a file with content"
    copy:
      dest: "/tmp/test"
      content: "Fact={{ ansible_local['meta-data']['foo'] | default('not found') }}\n"
